AppView/Controllers/VoucherDetailController.cs
using AppData.data;
using AppData.model;
using AppData.Serviece.Implements;
using AppData.ViewModal.HoaDon;
using AppData.ViewModal.VoucherVM;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using Newtonsoft.Json;
using System.Security.Claims;
using System.Text;

namespace AppView.Controllers
{
    public class VoucherDetailController : Controller
    {
        private readonly ILogger<VoucherDetailController> _logger;
        HttpClient _client = new HttpClient();
        private readonly MyDbContext _context;
        private readonly VoucherDetailServices _voucher;
        private readonly IWebHostEnvironment _hosting;

        public VoucherDetailController(ILogger<VoucherDetailController> logger, IWebHostEnvironment hosting)
        {
            _context = new MyDbContext();
            _logger = logger;
            _hosting = hosting;
            _voucher = new VoucherDetailServices();
        }

        public Guid IDNguoiDung()
        {
            ClaimsPrincipal claimsPrincipal = HttpContext.User;

            var userlogin = HttpContext.User;
            var email = userlogin.FindFirstValue(ClaimTypes.Email);
            var user = _context.Users.FirstOrDefault(c => c.Email == email);
            return user.Id;
        }
        [HttpGet]
        public ActionResult GetAllVoucherDetail()
        {
            string url = "https://localhost:7214/api/VoucherDetail/GetAll";
            var respon = _client.GetAsync(url).Result;
            var data = respon.Content.ReadAsStringAsync().Result;
            List<VoucherDetail> lstVoucher = JsonConvert.DeserializeObject<List<VoucherDetail>>(data);
            return View(lstVoucher);
        }

        [HttpGet]
        [HttpPost]
        public async Task<ActionResult> CreateVoucherDetail(VoucherDetail voucherDetail)
        {
            string url = $"https://localhost:7214/api/VoucherDetail/Create";
            var obj = JsonConvert.SerializeObject(voucherDetail);
            StringContent content = new StringContent(obj, Encoding.UTF8, "application/json");
            HttpResponseMessage httpResponseMessage = await _client.PostAsync(url, content);
            return View("CreateVoucherDetail");
        }

        [HttpGet]
        [HttpPut]
        public async Task<ActionResult> EditVoucherDetail(VoucherDetail voucherDetail)
        {
            string url = $"https://localhost:7214/api/VoucherDetail/Edit/{voucherDetail.Id}";
            var obj = JsonConvert.SerializeObject(voucherDetail);
            StringContent content = new StringContent(obj, Encoding.UTF8, "application/json");
            HttpResponseMessage httpResponseMessage = await _client.PutAsync(url, content);
            return View("GetAllVoucherDetail");
        }

        [HttpGet]
        [HttpDelete]
        public async Task<ActionResult> DeleteVoucherDetail(VoucherDetail voucherDetail)
        {
            string url = $"https://localhost:7214/api/VoucherDetail/Delete/{voucherDetail.Id}";
            var obj = JsonConvert.SerializeObject(voucherDetail);
            StringContent content = new StringContent(obj, Encoding.UTF8, "application/json");
            HttpResponseMessage httpResponseMessage = await _client.PutAsync(url, content);

            return RedirectToAction("GellAllCVoucherDetail");
        }
        [HttpGet]
        public async Task<ActionResult> GetListVoucherViewModel()
        {
            string url = $"https://localhost:7214/api/VoucherDetail/GetlistVoucherViewModel";
            return View();
        }
        [HttpGet]
        public async Task<ActionResult> GetListVoucherViewModelByIdNguoiDung()
        {
            var idnguoidung = IDNguoiDung();
            string url = $"https://localhost:7214/api/VoucherDetail/GetlistVoucherViewModelByIdNguoiDung?idnguoidung={idnguoidung}";
            var respone = await _client.GetAsync(url);
            var data = await respone.Content.ReadAsStringAsync();
            List<VoucherDetailHoanThien> listVoucher = JsonConvert.DeserializeObject<List<VoucherDetailHoanThien>>(data);
            return View(listVoucher);
        }
        [HttpGet]
        public ActionResult GetVoucherViewModelById(Guid Idvoucher)
        {
            string url = $"https://localhost:7214/api/VoucherDetail/GetlistVoucherViewModelByID?IdVoucherDetail={Idvoucher}";
            var respone =  _client.GetAsync(url).Result;
            var data =  respone.Content.ReadAsStringAsync().Result;
            VoucherDetailHoanThien VoucherDeatail = JsonConvert.DeserializeObject<VoucherDetailHoanThien>(data);
            return View(VoucherDeatail);
        }
        [HttpGet]
        public ActionResult GetVoucherViewModelByName(string Mavoucher)
        {
            string url = $"https://localhost:7214/api/VoucherDetail/GetListVoucherViewModelByName?MaVoucher={Mavoucher}";
            var respone = _client.GetAsync(url).Result;
            var data = respone.Content.ReadAsStringAsync().Result;
            VoucherDetailHoanThien VoucherDeatail = JsonConvert.DeserializeObject<VoucherDetailHoanThien>(data);
            return Json(VoucherDeatail);
        }
    }
}

AppView/Views/VoucherDetail/CreateVoucherDetail.cshtml
@model AppData.model.VoucherDetail

@{
    ViewData["Title"] = "CreateVoucherDetail";
}

<h1>CreateVoucherDetail</h1>

<h4>VoucherDetail</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateVoucherDetail">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Soluong" class="control-label"></label>
                <input asp-for="Soluong" class="form-control" />
                <span asp-validation-for="Soluong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="status" class="control-label"></label>
                <input asp-for="status" class="form-control" />
                <span asp-validation-for="status" class="text-danger"></span>
            </div> 
            <div class="form-group">
                <label asp-for="IdVoucher" class="control-label"></label>
                <input asp-for="IdVoucher"  class="form-control" />
                <span asp-validation-for="IdVoucher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdNguoiDung" class="control-label"></label>
                <input asp-for="IdNguoiDung"  class="form-control" />
                <span asp-validation-for="IdNguoiDung" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppView/Views/VoucherDetail/DeleteVoucherDetail.cshtml
@model AppData.model.VoucherDetail

@{
    ViewData["Title"] = "DeleteVoucherDetail";
}

<h1>DeleteVoucherDetail</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VoucherDetail</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Soluong)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Soluong)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.status)
        </dd>
         <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdVoucher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdVoucher)
        </dd>
         <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdNguoiDung)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdNguoiDung)
        </dd>
    </dl>
    
    <form asp-action="DeleteVoucher">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AppView/Views/VoucherDetail/EditVoucherDetail.cshtml
@model AppData.model.VoucherDetail

@{
    ViewData["Title"] = "EditVoucherDetail";
}

<h1>EditVoucherDetail</h1>

<h4>VoucherDetail</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditVoucherDetail">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Soluong" class="control-label"></label>
                <input asp-for="Soluong" class="form-control" />
                <span asp-validation-for="Soluong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="status" class="control-label"></label>
                <input asp-for="status" class="form-control" />
                <span asp-validation-for="status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdVoucher" class="control-label"></label>
                <input asp-for="IdVoucher"  class="form-control" />
                <span asp-validation-for="IdVoucher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdNguoiDung" class="control-label"></label>
                <input asp-for="IdNguoiDung"  class="form-control" />
                <span asp-validation-for="IdNguoiDung" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppView/Views/VoucherDetail/GetAllVoucherDetail.cshtml
@model IEnumerable<AppData.model.VoucherDetail>

@{
    ViewData["Title"] = "GetAllVoucherDetail";
}

<h1>GetAllVoucherDetail</h1>

<p>
    <a asp-action="CreateVoucherDetail">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Soluong)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.status)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.IdVoucher)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.IdNguoiDung)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Soluong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdVoucher)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdNguoiDung)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {  id=item.Id }) |
                @Html.ActionLink("Details", "Details", new {  id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

AppView/Views/VoucherDetail/GetListVoucherViewModelByIdNguoiDung.cshtml
@model IEnumerable<AppData.ViewModal.VoucherVM.VoucherDetailHoanThien>
<style type="text/css">
    .vc_my-wallet-page-vouchers_noneRightBorder {
        border-right: none;
    }
    .vc_Logo_imageLogo {
        align-items: center;
        display: flex;
        justify-content: center;
    }
    .vc_VoucherStandardTemplate_left {
        align-items: center;
        box-sizing: border-box;
        display: flex;
        flex-direction: column;
        justify-content: center;
        position: relative;
        width: var(--vc-card-height,7.375rem);
    }
    .vc_my-wallet-page-vouchers_shopeeVoucher {
        --vc-icon-text-color: #fff;
        --vc-card-left-border-color: #ee4d2d;
        --vc-card-left-fill-color: #ee4d2d;
        --vc-card-right-border-color: #e8e8e8;
        --vc-card-background-color: #fff;
    }
    .vc_Card_card, .vc_Card_container {
        width: var(--vc-card-width,28.375rem);
    }
    .vc_my-wallet-page-vouchers_pc {
        --vc-card-width: 28.375rem;
        --vc-card-height: 7.375rem;
        --vc-card-sawtooth-margin: 0.25rem;
        --vc-template-box-shadow: 0.125rem 0.125rem 0.3125rem rgba(0,0,0,.07);
        --vc-logo-size: 3.5rem;
        --vc-expiry-font-size: 0.75rem;
        --vc-expiry-line-height: 0.875rem;
        --vc-expiry-margin-top: 0.25rem;
        --vc-main-title-font-size: 1rem;
        --vc-main-title-line-height: 1.25rem;
        --vc-subtitle-font-size: 0.875rem;
        --vc-subtitle-line-height: 1rem;
        --vc-product-scope-font-size: 0.75rem;
        --vc-product-scope-line-height: 0.875rem;
        --vc-product-scope-padding: 0.0625rem 0.25rem;
        --vc-icon-text-font-size: 0.75rem;
        --vc-icon-text-line-height: 0.875rem;
        --vc-icon-text-max-height: 1.75rem;
        --vc-icon-text-margin-top: 0.25rem;
        --vc-radio-button-border: 0.0625rem solid rgba(0,0,0,.14);
        --vc-radio-button-box-shadow: var(--black2) 0 0.125rem 0 0;
    }
</style>
@{
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-6 vc_Card_container vc_my-wallet-page-vouchers_pc vc_my-wallet-page-vouchers_shopeeVoucher" data-testid="vcCard">
                    <div class="card">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="vc_my-wallet-page-vouchers_noneRightBorder vc_VoucherStandardTemplate_left" role="presentation">
                                    <div data-testid="vcLogo" class="vc_Logo_imageLogo" data-target="shop_icon">
                                        <img class="vc_Logo_logo" src="	https://cf.shopee.vn/file/e6a3b7beffa95ca492926978d5235f79" alt="Logo" />
                                    </div>
                                    <div data-testid="vcIconText" class="vc_IconText_iconText vc_IconText_white vc_IconText_defaultLine" data-cy="voucher_card_icon_text" style="text-transform: initial;">SHOPEE</div>
                                </div>
                            </div>
                            <div class="col-md-9">
                                <div class="card-body">
                                    <h4 class="card-title">John Doe</h4>
                                    <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
                                    <a href="#" class="btn btn-primary">See Profile</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th style="display:none;">
                    @Html.DisplayNameFor(model => model.IDVoucherDetail)
                </th>
                <th>
                    Mã Voucher
                </th>
                <th>
                    Số lượng
                </th>
                <th>
                    Trạng thái
                </th>
                <th style="display:none;">
                    @Html.DisplayNameFor(model => model.IDVoucher)
                </th>
                <th style="display:none;">
                    @Html.DisplayNameFor(model => model.IDNguoiDuong)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td style="display:none;">
                        @Html.DisplayFor(modelItem => item.IDVoucherDetail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MaVoucher)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Soluong)
                    </td>
                    <td>
                        @if (item.TrangThai == 0)
                        {
                            <p>Đã hết hạn</p>
                        }
                        else
                        {
                            <p>Sử dụng</p>
                        }
                    </td>
                    <td style="display:none;">
                        @Html.DisplayFor(modelItem => item.IDVoucher)
                    </td>
                    <td style="display:none;">
                        @Html.DisplayFor(modelItem => item.IDNguoiDuong)
                    </td>
                    <td>
                        <a href="@Url.Action("GetVoucherViewModelById","VoucherDetail",new { Idvoucher = item.IDVoucherDetail})">
                            <i class="fas fa-eye" style="color: #0084ff;"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

AppView/Views/VoucherDetail/GetVoucherViewModelById.cshtml
@model AppData.ViewModal.VoucherVM.VoucherDetailHoanThien;
@{

}
<div class="container">
    <div class="">

    </div>
</div>