AppView/Controllers/GioHangController.cs
using AppData.data;
using AppData.model;
using AppData.Serviece.Implements;
using AppData.Serviece.Interfaces;
using AppData.Session;
using AppData.ViewModal.GioHangChiTietViewModel;
using AppData.ViewModal.SanPhamChiTietVM;
using AppData.ViewModal.Usermodalview;
using AppData.ViewModal.VoucherVM;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Security.Policy;
using System.Text;

namespace AppView.Controllers
{
    public class GioHangController : Controller
    {
        HttpClient _client = new HttpClient();
        private readonly IGioHangCTService ghctservice;
        private readonly MyDbContext _context;


        public GioHangController()
        {
            //_nguoiDungServiece = nguoiDungServiece;
            ghctservice = new GioHangCTService();
            _context = new MyDbContext();

        }

        // GET: GioHangController
        public ActionResult Index()
        {
            return View();

        }
        public Guid IDNguoiDung()
        {
            ClaimsPrincipal claimsPrincipal = HttpContext.User;

            var userlogin = HttpContext.User;
            var email = userlogin.FindFirstValue(ClaimTypes.Email);
            var user = _context.Users.FirstOrDefault(c => c.Email == email);
            return user.Id;
        }
        // GET: GioHangController/Details/5
        public async Task<ActionResult> GetallGH()
        {
            var response = await _client.GetFromJsonAsync<List<GioHang>>($"https://localhost:7214/api/GioHang/GetAll");
            return View(response);
        }

        [HttpGet]
        public async Task<ActionResult> GetGioHangChiTiet(GioHang gh)
        {
            var idnguoidung = IDNguoiDung();
            string url = $"https://localhost:7214/api/GioHangCT/GetAllFullGioHangChiTiet?IDnguoiDung={idnguoidung}";
            var repos = await _client.GetAsync(url);
            var data = await repos.Content.ReadAsStringAsync();
            List<GioHangChiTietViewModel> lstghct = JsonConvert.DeserializeObject<List<GioHangChiTietViewModel>>(data);
            return View(lstghct);


        }
        // GET: GioHangController/Create
        public async Task<ActionResult> CreateGioHang(GioHang gh)
        {
            string url = $"https://localhost:7214/api/GioHang/Create?{gh.Id}";


            var obj = JsonConvert.SerializeObject(gh);
            StringContent content = new StringContent(obj, Encoding.UTF8, "application/json");
            HttpResponseMessage httpResponseMessage = await _client.PostAsync(url, content);
            if (httpResponseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("GetallGH");
            }
            else
            {
                return View("CreateGioHang");
            }
        }

        // POST: GioHangController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: GioHangController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: GioHangController/Edit/5
        [HttpGet]
        public IActionResult UpdateGH(Guid Id)
        {
            string apiurl = $"https://localhost:7214/api/GioHang/Update/{Id}";

            var respone = _client.GetAsync(apiurl).Result;
            var data = respone.Content.ReadAsStringAsync().Result;
            var sp = JsonConvert.DeserializeObject<GioHang>(data);





            return View(sp);

        }
        [HttpPost]
        public IActionResult UpdateGH(Guid id, GioHang gh)
        {
            //string url = $"https://localhost:7214/api/Combo/Update/{cb.Id}";
            //var obj = JsonConvert.SerializeObject(cb);
            //StringContent content = new StringContent(obj, Encoding.UTF8, "application/json");
            //HttpResponseMessage httpResponseMessage = await _client.PutAsync(url, content);

            //return RedirectToAction("GetlistComBO");
            string apiurl = $"https://localhost:7214/api/GioHang/Update/{id}?Ten={gh.GhiChu}";

            var obj = JsonConvert.SerializeObject(gh);
            StringContent content = new StringContent(obj, Encoding.UTF8, "application/json");
            var respone = _client.PutAsJsonAsync(apiurl, obj).Result;
            if (respone.IsSuccessStatusCode)
            {
                return RedirectToAction("GetlistComBO");
            }
            else
            {
                return RedirectToAction("GetallGH");
            }


        }

        // GET: GioHangController/Delete/5
        public async Task<ActionResult> DeleteAsync(GioHang gio)
        {
            string url = $"https://localhost:7214/api/GioHang/Delete/{gio.Id}";
            var obj = JsonConvert.SerializeObject(gio);
            StringContent content = new StringContent(obj, Encoding.UTF8, "application/json");
            HttpResponseMessage httpResponseMessage = await _client.PutAsync(url, content);

            return RedirectToAction("GetallGH", "QuanTri");
        }

        // POST: GioHangController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public async Task<ActionResult> XoaSanPhamKhoiGioHang(Guid id)
        {
            string url = $"https://localhost:7214/api/GioHangCT/XoaSanPham?id={id}";
            var reposs = await _client.GetAsync(url);
            HttpResponseMessage Xoa = await _client.DeleteAsync(url);
            if (Xoa.IsSuccessStatusCode)
            {
                // Xóa thành công
                TempData["success"] = "Xóa thành công.";
                return RedirectToAction("GetGioHangChiTiet");
            }
            else
            {
                // Xử lý lỗi, ví dụ: hiển thị thông báo lỗi
                TempData["Error"] = "Xóa không thành công.";
                return RedirectToAction("GetGioHangChiTiet");
            }
        }
        [HttpGet]
        [HttpPost]
        public ActionResult DecreaseButton(Guid id, int soluong)
        {
            Guid Idnguoidung = IDNguoiDung();
            //var idnguoidung = Guid.Parse("911a9476-05be-4a4f-8325-2ea61766e2a0");
            GioHangChiTiet ghct = ghctservice.GetAllGioHangTheoNguoiDungDangNhap(Idnguoidung).FirstOrDefault(c => c.Id == id);
            if (ghct != null)
            {
                if (soluong > 0)
                {
                    soluong--;
                }
                ghct.SoLuong = soluong;
            }
            ghctservice.EditSoluong(id, soluong);
            return RedirectToAction("GetGioHangChiTiet");
        }
        [HttpGet]
        [HttpPost]
        public ActionResult IncreaseButton(Guid id, int soluong)
        {
            Guid Idnguoidung = IDNguoiDung();
            //var idnguoidung = Guid.Parse("911a9476-05be-4a4f-8325-2ea61766e2a0");
            GioHangChiTiet ghct = ghctservice.GetAllGioHangTheoNguoiDungDangNhap(Idnguoidung).FirstOrDefault(c => c.Id == id);
            soluong++;
            if (ghct != null)
            {
                ghct.SoLuong = soluong;
            }
            ghctservice.EditSoluong(id, soluong);
            return RedirectToAction("GetGioHangChiTiet");
        }
        // Thanh toán

        // Lấy hết thành phố tỉnh
        [HttpPost]
        public List<ThongTinThanhPho> GetAllTinh()
        {
            string token = "be8ee160-008a-11ee-a281-3aa62a37e0a5";
            _client.DefaultRequestHeaders.Add("token", token);
            List<ThongTinThanhPho> thongtintp = new List<ThongTinThanhPho>();
            var urlTinhThanhPho = "https://online-gateway.ghn.vn/shiip/public-api/master-data/province";
            HttpResponseMessage response = _client.GetAsync(urlTinhThanhPho).Result;
            // lấy ID tỉnh
            if (response.IsSuccessStatusCode)
            {
                var provinces = response.Content.ReadAsStringAsync().Result; ;

                JObject jsonObject = JObject.Parse(provinces);

                // Lấy danh sách tỉnh/thành phố từ đối tượng JSON
                JArray provinceArray = (JArray)jsonObject["data"];


                if (provinceArray != null)
                {
                    foreach (JObject province in provinceArray)
                    {
                        ThongTinThanhPho thongTinThanhPho = new ThongTinThanhPho();
                        thongTinThanhPho.Id = Convert.ToInt32(province["ProvinceID"]);
                        thongTinThanhPho.Name = Convert.ToString(province["ProvinceName"]);
                        thongtintp.Add(thongTinThanhPho);
                    }
                }
                ViewBag.thongtin = thongtintp;
            }
            HttpContext.Session.Set("ThanhPho", thongtintp);
            return thongtintp;
        }


        //[HttpGet]
        ////Lấy hết quận huyện
        //public List<ThongTinQuanHuyen> GetQuanHuyen(int? idtp)
        //{

        //    return thongtinquanhuyen;
        //}
        // Lấy Id thành phố tỉnh 
        [HttpPost]
        public IActionResult NhanIDTinh(int IdThanhPho)
        {
            List<ThongTinQuanHuyen> thongtinquanhuyen = new List<ThongTinQuanHuyen>();
            string token = "be8ee160-008a-11ee-a281-3aa62a37e0a5";
            _client.DefaultRequestHeaders.Add("token", token);

AppView/Views/GioHang/CreateGioHang.cshtml
@model AppData.model.GioHang

@{
    ViewData["Title"] = "CreateGioHang";
}

<h1>CreateGioHang</h1>

<h4>GioHang</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateGioHang">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           @* <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="GhiChu" class="control-label"></label>
                <input asp-for="GhiChu" class="form-control" />
                <span asp-validation-for="GhiChu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdNguoiDung" class="control-label"></label>
                <input asp-for="IdNguoiDung" class="form-control" />
                <span asp-validation-for="IdNguoiDung" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppView/Views/GioHang/DeleteAsync.cshtml
@model AppData.model.GioHang

@{
    ViewData["Title"] = "DeleteAsync";
}

<h1>DeleteAsync</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GioHang</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GhiChu)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GhiChu)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdNguoiDung)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdNguoiDung)
        </dd>
    </dl>
    
    <form asp-action="DeleteAsync">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AppView/Views/GioHang/EditAsync.cshtml
@model AppData.model.GioHang

@{
    ViewData["Title"] = "EditAsync";
}

<h1>EditAsync</h1>

<h4>GioHang</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditAsync">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GhiChu" class="control-label"></label>
                <input asp-for="GhiChu" class="form-control" />
                <span asp-validation-for="GhiChu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdNguoiDung" class="control-label"></label>
                <input asp-for="IdNguoiDung" class="form-control" />
                <span asp-validation-for="IdNguoiDung" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppView/Views/GioHang/GetGioHangChiTiet.cshtml
@model IEnumerable<AppData.ViewModal.GioHangChiTietViewModel.GioHangChiTietViewModel>

@{

}
<link type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
<script type="text/javascript" src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<link type="text/css" href="~/adminlte-3.2.0/plugins/fontawesome-free/css/all.min.css" rel="stylesheet" />
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
<style type="text/css">
    body {
        margin-top: 20px;
        background-color: #f1f3f7;
    }

    .avatar-lg {
        height: 5rem;
        width: 5rem;
    }

    .font-size-18 {
        font-size: 18px !important;
    }

    .text-truncate {
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }

    a {
        text-decoration: none !important;
    }

    .w-xl {
        min-width: 160px;
    }

    .card {
        margin-bottom: 24px;
        -webkit-box-shadow: 0 2px 3px #e4e8f0;
        box-shadow: 0 2px 3px #e4e8f0;
    }

    .card {
        position: relative;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: 1px solid #eff0f2;
        border-radius: 1rem;
    }
</style>
@if (TempData["success"] != null)
{
    <div class="alert alert-success">@TempData["success"]</div>
}
@if (TempData["Error"] != null)
{
    <div class="alert alert-danger">@TempData["Error"]</div>
}
<body>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/5.3.45/css/materialdesignicons.css" integrity="sha256-NAxhqDvtY0l4xn+YVa6WjAcmd94NNfttjNsDmNatFVc=" crossorigin="anonymous" />
    <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet">
    <div class="container">
        <div class="row">
            <div class="col-xl-8">
                @foreach (var item in Model)
                {
                    double Total = 0;
                    Total = (double)item.Soluong * (double)item.GiaSanPham;

                    <div>
                        <div class="card border shadow-none">
                            <div class="card-body">
                                <div class="d-flex align-items-start border-bottom pb-3">
                                    <div class="me-4">
                                        <img src="@Url.Action("DisplayImage", "QuanTri", new { imagePath = item.pathImage })" alt="Image" class="avatar-lg rounded" />
                                    </div>
                                    <div class="flex-grow-1 align-self-center overflow-hidden">
                                        <div>
                                            <h5 class="text-truncate font-size-18"><a href="#" class="text-dark">@item.TenSanPham</a></h5>
                                            <p class="text-muted mb-0">
                                                <i class="bx bxs-star text-warning"></i>
                                                <i class="bx bxs-star text-warning"></i>
                                                <i class="bx bxs-star text-warning"></i>
                                                <i class="bx bxs-star text-warning"></i>
                                                <i class="bx bxs-star-half text-warning"></i>
                                            </p>
                                            <p class="mb-0 mt-1">Color : <span class="fw-medium">@item.Mausac</span></p>
                                            <p class="mb-0 mt-1">Size : <span class="fw-medium">@item.Size</span></p>
                                        </div>
                                    </div>
                                    <div class="flex-shrink-0 ms-2">
                                        <ul class="list-inline mb-0 font-size-16">
                                            <li class="list-inline-item">
                                                <a href="@Url.Action("XoaSanPhamKhoiGioHang","GioHang",new { id = item.ID})" onclick="return confirm('Bạn có chắc muốn xóa sản phẩm này?');" class="text-muted px-1">
                                                    <i class="fas fa-trash" style="color: #ff0000;"></i>
                                                </a>
                                            </li>
                                            <li class="list-inline-item">
                                                <a href="#" class="text-muted px-1">
                                                    <i class="mdi mdi-heart-outline"></i>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <div>
                                    <div class="row">
                                        <div class="col-md-3">
                                            <div class="mt-3">
                                                <p class="text-muted mb-2">Giá sản phẩm</p>
                                                <h5 class="mb-0 mt-2"><span class="text-muted me-2"><del class="font-size-16 fw-normal">@item.TienGiamGia.ToString("C0", new System.Globalization.CultureInfo("vi-VN"))</del></span>@item.GiaSanPham.ToString("C0", new System.Globalization.CultureInfo("vi-VN"))</h5>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="mt-3">
                                                <p class="text-muted mb-2" style="margin-left:40px;">Số lượng</p>
                                                <div class="d-inline-flex">
                                                    <a class="btn" href="@Url.Action("DecreaseButton","GioHang",new { id = item.ID , soluong =item.Soluong})" id="decreaseButton"><i class="fas fa-minus-circle" style="color: #538ae9;"></i></a>
                                                    <input type="number" value="@item.Soluong" min="0" style="width:120px;">
                                                    <a class="btn" id="increaseButton" href="@Url.Action("IncreaseButton","GioHang",new { id = item.ID , soluong =item.Soluong})"><i class="fas fa-plus-circle" style="color: #538ae9;"></i></a>
                                                </div>
                                            </div>
                                        </div>
@*                                        <div class="col-md-3">
                                            <div class="mt-3">
                                                <a class="btn btn-primary" style="margin-top:32px;">Cập nhật</a>
                                            </div>
                                        </div>*@
                                        <div class="col-md-3">
                                            <div class="mt-3">
                                                <p class="text-muted mb-2">Total</p>
                                                <h5>@Total.ToString("C0", new System.Globalization.CultureInfo("vi-VN"))</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="col-xl-4">
                @{
                    double ThanhTien = Model.Sum(m => (double)m.Soluong * (double)m.GiaSanPham) - Model.Sum(m => (double)m.TienGiamGia);
                }
                <div>
                    <div class="mt-5 mt-lg-0">
                        <div class="card border shadow-none">
                            <div class="card-header bg-transparent border-bottom py-3 px-4">
                                <h5 class="font-size-16 mb-0">Tính tiền <span class="float-end">#MN0124</span></h5>
                            </div>
                            <div class="card-body p-4 pt-2">
                                <div class="table-responsive">
                                    <table class="table mb-0">
                                        <tbody>
                                            <tr>
                                                <td>Tổng tiền :</td>
                                                <td class="text-end">@Model.Sum(m => (double) m.Soluong * (double) m.GiaSanPham).ToString("C0", new System.Globalization.CultureInfo("vi-VN"))</td>
                                            </tr>
                                            <tr>
                                                <td>Tiền giảm giá : </td>
                                                <td class="text-end">- @Model.Sum(m => (double) m.TienGiamGia * m.Soluong).ToString("C0", new System.Globalization.CultureInfo("vi-VN"))</td>
                                            </tr>
                                            <tr class="bg-light">
                                                <td>Thành tiền :</td>
                                                <td class="text-end">@ThanhTien.ToString("C0", new System.Globalization.CultureInfo("vi-VN"))</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row my-4">
                        <div class="col-sm-6">
                            <a asp-controller="QuanTri" asp-action="GellAllSanPhamCT" class="btn btn-link text-muted">
                                <i class="mdi mdi-arrow-left me-1"></i> Continue Shopping
                            </a>
                        </div>
                        <div class="col-sm-6">
                            <div class="text-sm-end mt-2 mt-sm-0">
                                <a asp-controller="GioHang" asp-action="ThanhToan" class="btn btn-success">
                                    <i class="mdi mdi-cart-outline me-1"></i> Checkout
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>



        </div>
    </div>
</body>

AppView/Views/GioHang/GetallGH.cshtml
@model IEnumerable<AppData.model.GioHang>

@{
    ViewData["Title"] = "GetallGH";
}

<h1>GetallGH</h1>

<p>
    <a asp-action="CreateGioHang">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GhiChu)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdNguoiDung)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GhiChu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdNguoiDung)
            </td>
            <td>
                    @Html.ActionLink("Edit", "UpdateGH", new { id=item.Id  }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>